### ISSUE TITLE
Error when installing via pipenv

### ISSUE THREAD

**Issue by senniraf** [koehlma/momba#12]
Hi, I'm currently trying to install momba via pipenv and I'm getting the following error:

```
Installing momba...
Resolving momba...
Added momba to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠋ Locking...False
ERROR:pip.subprocessor:Getting requirements to build wheel exited with 1
[ResolutionFailure]:   File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 645, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 612, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 592, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 918, in resolve_deps
[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(
[ResolutionFailure]:   File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 691, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 448, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Getting requirements to build wheel exited with 1

Traceback (most recent call last):
  File "/home/raffael/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 209, in install
    do_install(
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 297, in do_install
    raise e
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 281, in do_install
    do_init(
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/routines/install.py", line 672, in do_init
    do_lock(
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/routines/lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 859, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
  File "/home/raffael/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 728, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
```

I'm using pipenv and have the following packages installed:
```
pip==23.2.1
setuptools==68.2.2
wheel==0.42.0
```

Best regards
Raffael

**Comment by koehlma** [comment]
I am not sure what the problem may be. Can you please share your `Pipfile`. The error message hints at incompatible dependencies, so you may be a version of another package which may be incompatible with Momba.

**Comment by senniraf** [comment]
My `Pipfile` is "empty":
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.10"
```

The error was reproducible in a "fresh" ubuntu docker container. So there are no system packages which may be incompatible.

**Comment by koehlma** [comment]
Thanks for the clarification. I was able to reproduce the problem. Indeed, something was an error with one of Momba's dependencies (`immutables`) and Python 3.10. I have not used Momba myself for a while as I am currently focused on writing my thesis.

You should now be able to get a working installation with:
```toml
[packages]
momba = { version = ">=0.6.9", extras = ["engine"] }
```

**Comment by senniraf** [comment]
Thank you for your support! It worked. I wish you every success in writing your thesis!
